export const APPWRITE_ENDPOINT = import.meta.env.VITE_APPWRITE_ENDPOINT;
export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID;
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_RANTS_DATABASE_ID;
export const APPWRITE_COLLECTION_ID = import.meta.env.VITE_APPWRITE_RANTS_COLLECTION_ID;

export const APPWRITE_WISHLIST_COLLECTION_ID = import.meta.env.VITE_APPWRITE_WISHLIST_COLLECTION_ID;

export const APPWRITE_MEMORIES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_MEMORIES_COLLECTION_ID;
export const APPWRITE_MEMORIES_BUCKET_ID = import.meta.env.VITE_APPWRITE_MEMORIES_BUCKET_ID;